# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-15 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0076_auto_20190215_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobflavor',
            name='memory',
            field=models.IntegerField(default=1, help_text='How much memory in GiB is assigned to this flavor'),
        ),
    ]
