# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-14 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0076_auto_20190214_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VMStrategy',
            new_name='JobStrategy',
        ),
        migrations.AlterModelOptions(
            name='jobstrategy',
            options={'verbose_name_plural': 'Job Strategies'},
        ),
    ]
