# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-15 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_jobflavor_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vm_flavor',
            new_name='job_flavor',
        ),
        migrations.RenameField(
            model_name='jobquestionnaire',
            old_name='vm_flavor',
            new_name='job_flavor',
        ),
        migrations.RenameField(
            model_name='vmstrategy',
            old_name='vm_flavor',
            new_name='job_flavor',
        ),
    ]
