# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_auto_20190214_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VMSettings',
            new_name='JobSettings',
        ),
        migrations.AlterModelOptions(
            name='jobsettings',
            options={'verbose_name_plural': 'Job Settings Collections'},
        ),
        migrations.AlterField(
            model_name='job',
            name='vm_settings',
            field=models.ForeignKey(help_text='Collection of settings to use when running this job', on_delete=django.db.models.deletion.CASCADE, to='data.JobSettings'),
        ),
    ]
