# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0078_auto_20190215_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_flavor',
            field=models.ForeignKey(help_text='Cpu/Memory to use when running the workflow associated with this job', on_delete=django.db.models.deletion.CASCADE, to='data.JobFlavor'),
        ),
        migrations.AlterField(
            model_name='jobflavor',
            name='memory',
            field=models.CharField(default='1Gi', help_text='How much memory in GiB is assigned to this flavor', max_length=12),
        ),
        migrations.AlterField(
            model_name='jobquestionnaire',
            name='job_flavor',
            field=models.ForeignKey(help_text='Cpu/Memory to use when running the workflow for this questionnaire', on_delete=django.db.models.deletion.CASCADE, to='data.JobFlavor'),
        ),
    ]
