# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-15 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0079_auto_20190215_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vm_settings',
            new_name='job_settings',
        ),
        migrations.RenameField(
            model_name='jobquestionnaire',
            old_name='vm_settings',
            new_name='job_settings',
        ),
        migrations.RenameField(
            model_name='vmstrategy',
            old_name='vm_settings',
            new_name='job_settings',
        ),
    ]
