# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-15 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0080_move_job_settings_to_vm_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsettings',
            name='cloud_settings',
        ),
        migrations.RemoveField(
            model_name='jobsettings',
            name='cwl_base_command',
        ),
        migrations.RemoveField(
            model_name='jobsettings',
            name='cwl_post_process_command',
        ),
        migrations.RemoveField(
            model_name='jobsettings',
            name='cwl_pre_process_command',
        ),
        migrations.RemoveField(
            model_name='jobsettings',
            name='image_name',
        ),
    ]
