# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-15 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_auto_20190215_1919'),
        ('data', '0079_auto_20190215_2118'),
    ]

    operations = [
    ]
