# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-15 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_auto_20190215_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vm_flavor',
            new_name='job_flavor',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='vm_settings',
            new_name='job_settings',
        ),
        migrations.RenameField(
            model_name='jobquestionnaire',
            old_name='vm_flavor',
            new_name='job_flavor',
        ),
        migrations.RenameField(
            model_name='jobquestionnaire',
            old_name='vm_settings',
            new_name='job_settings',
        ),
        migrations.RenameField(
            model_name='jobstrategy',
            old_name='vm_flavor',
            new_name='job_flavor',
        ),
        migrations.RenameField(
            model_name='jobstrategy',
            old_name='vm_settings',
            new_name='job_settings',
        ),
    ]
