# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_merge_20190215_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(help_text='Name of the VM Image to launch', max_length=255)),
                ('cwl_base_command', models.TextField(help_text="JSON-encoded command array to run the  image's installed CWL engine")),
                ('cwl_post_process_command', models.TextField(blank=True, help_text='JSON-encoded command array to run after workflow completes')),
                ('cwl_pre_process_command', models.TextField(blank=True, help_text='JSON-encoded command array to run before cwl_base_command')),
                ('cloud_settings', models.ForeignKey(help_text='Cloud settings ', on_delete=django.db.models.deletion.CASCADE, to='data.CloudSettings')),
            ],
        ),
        migrations.AddField(
            model_name='jobsettings',
            name='lando_connection',
            field=models.ForeignKey(help_text='Lando connection to use for this job settings', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.LandoConnection'),
        ),
        migrations.AddField(
            model_name='jobsettings',
            name='settings_type',
            field=models.TextField(choices=[('vm', 'VM Job Settings'), ('k8s', 'K8s Job Settings')], default='vm'),
        ),
        migrations.AlterField(
            model_name='jobflavor',
            name='memory',
            field=models.CharField(default='1Gi', help_text='How much memory in k8s units to be use when running a job with this flavor', max_length=12),
        ),
        migrations.AddField(
            model_name='vmcommand',
            name='job_settings',
            field=models.ForeignKey(help_text='job settings', on_delete=django.db.models.deletion.CASCADE, related_name='vm_command', to='data.JobSettings'),
        ),
    ]
