# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-15 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_auto_20190215_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmcommand',
            name='job_settings',
            field=models.ForeignKey(help_text='job settings', on_delete=django.db.models.deletion.CASCADE, related_name='vm_command', to='data.JobSettings'),
        ),
    ]
