# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 14:34
from __future__ import unicode_literals

from django.db import migrations


def populate_job_settings_lando_connection(apps, schema_editor):
    LandoConnection = apps.get_model("data", "LandoConnection")
    JobSettings = apps.get_model("data", "JobSettings")
    if JobSettings.objects.count() > 0:
        lando_connection = LandoConnection.objects.first()
        for obj in JobSettings.objects.all():
            obj.lando_connection = lando_connection
            obj.save()


def populate_job_runtime_open_stack_from_job_settings(apps, schema_editor):
    JobSettings = apps.get_model("data", "JobSettings")
    JobRuntimeOpenStack = apps.get_model("data", "JobRuntimeOpenStack")
    for job_setting in JobSettings.objects.all():
        job_runtime_openstack = JobRuntimeOpenStack.objects.create(
            cloud_settings=job_setting.cloud_settings,
            image_name=job_setting.image_name,
            cwl_base_command=job_setting.cwl_base_command,
            cwl_post_process_command=job_setting.cwl_post_process_command,
            cwl_pre_process_command=job_setting.cwl_pre_process_command,
        )
        job_setting.job_runtime_openstack = job_runtime_openstack
        job_setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0083_new_models_for_k8s'),
    ]

    operations = [
        migrations.RunPython(populate_job_settings_lando_connection, migrations.RunPython.noop),
        migrations.RunPython(populate_job_runtime_open_stack_from_job_settings, migrations.RunPython.noop),
    ]
