# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 14:34
from __future__ import unicode_literals

from django.db import migrations


def populate_job_settings_lando_connection(apps, schema_editor):
    LandoConnection = apps.get_model("data", "LandoConnection")
    JobSettings = apps.get_model("data", "JobSettings")
    if JobSettings.objects.count() > 0:
        lando_connection = LandoConnection.objects.first()
        for obj in JobSettings.objects.all():
            obj.lando_connection = lando_connection
            obj.save()


def populate_vm_command_from_job_settings(apps, schema_editor):
    JobSettings = apps.get_model("data", "JobSettings")
    VMCommand = apps.get_model("data", "VMCommand")
    for obj in JobSettings.objects.all():
        VMCommand.objects.create(
            job_settings=obj,
            cloud_settings=obj.cloud_settings,
            image_name=obj.image_name,
            cwl_base_command=obj.cwl_base_command,
            cwl_post_process_command=obj.cwl_post_process_command,
            cwl_pre_process_command=obj.cwl_pre_process_command,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0083_auto_20190218_1434'),
    ]

    operations = [
        migrations.RunPython(populate_job_settings_lando_connection, migrations.RunPython.noop),
        migrations.RunPython(populate_vm_command_from_job_settings, migrations.RunPython.noop),
    ]
