# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0084_move_vm_fields_to_vm_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsettings',
            name='cloud_settings',
        ),
        migrations.RemoveField(
            model_name='jobsettings',
            name='cwl_base_command',
        ),
        migrations.RemoveField(
            model_name='jobsettings',
            name='cwl_post_process_command',
        ),
        migrations.RemoveField(
            model_name='jobsettings',
            name='cwl_pre_process_command',
        ),
        migrations.RemoveField(
            model_name='jobsettings',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='vmcommand',
            name='job_settings',
            field=models.OneToOneField(help_text='job settings', on_delete=django.db.models.deletion.CASCADE, related_name='vm_command', to='data.JobSettings'),
        ),
    ]
