# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_cleanup_moved_vm_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8sstepcommand',
            name='step_type',
            field=models.CharField(choices=[('stage_data', 'Stage Data'), ('run_workflow', 'Run Workflow'), ('organize_output', 'Organize Output'), ('save_output', 'Save Output'), ('record_output_project', 'Record Output Project')], max_length=255),
        ),
    ]
