# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_cleanup_moved_vm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversion',
            name='version_info_url',
            field=models.URLField(help_text='URL to documentation about this workflow version.', null=True),
        ),
        migrations.AlterField(
            model_name='workflowversion',
            name='version',
            field=models.CharField(max_length=255),
        ),
    ]
