# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_auto_20190218_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VMStrategy',
            new_name='JobStrategy',
        ),
    ]
