# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-02 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_cleanup_moved_vm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversion',
            name='type',
            field=models.CharField(choices=[('packed', 'Single-file packed CWL Workflow'), ('zipped', 'Zip archive containing CWL workflow and dependencies')], default='packed', max_length=255),
        ),
        migrations.RenameField(
            model_name='workflowversion',
            old_name='object_name',
            new_name='workflow_path'
        ),
        migrations.AlterField(
            model_name='workflowversion',
            name='url',
            field=models.URLField(help_text='URL to workflow file.'),
        ),
    ]
