# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-02 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0086_auto_20190402_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversion',
            name='workflow_path',
            field=models.CharField(blank=True, help_text="Path to the workflow file after extracting the archive (e.g. exomeseq-gatk4-2.0.0/exomeseq-gatk4.cwl) or for packed workflows, the name of the object to run (e.g. '#main')", max_length=255),
        ),
    ]
