# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-29 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0086_auto_20190329_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowversion',
            options={},
        ),
    ]
