# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0086_auto_20190218_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowconfiguration',
            old_name='default_vm_strategy',
            new_name='default_job_strategy',
        ),
    ]
