# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-20 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0086_auto_20190220_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobstrategy',
            options={'verbose_name_plural': 'Job Strategies'},
        ),
    ]
