# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-04 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0087_auto_20190329_2001'),
        ('data', '0087_auto_20190402_1722'),
    ]

    operations = [
    ]
