# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 19:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0087_auto_20190218_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sStepCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.TextField(choices=[('stage_data', 'Stage Data'), ('run_workflow', 'Run Workflow'), ('organize_output', 'Organize Output'), ('save_output', 'Save Output'), ('record_output_project', 'Record Output Project')])),
                ('image_name', models.CharField(help_text='Name of the image to run for this step', max_length=255)),
                ('cpu', models.IntegerField(help_text='Number of cpu to request when running this step')),
                ('memory', models.CharField(help_text='Memory in k8s units to request when running this step', max_length=255)),
                ('base_command', django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON array with base command to run')),
                ('job_settings', models.ForeignKey(help_text='job settings', on_delete=django.db.models.deletion.CASCADE, related_name='k8s_steps', to='data.JobSettings')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='k8sstepcommand',
            unique_together=set([('job_settings', 'step_type')]),
        ),
    ]
