# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_auto_20190218_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sCommandSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_settings', models.ForeignKey(help_text='job settings', on_delete=django.db.models.deletion.CASCADE, related_name='k8s_command_set', to='data.JobSettings')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='k8sstepcommand',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='k8scommandset',
            name='step_commands',
            field=models.ManyToManyField(help_text='Steps to be used by this set', to='data.K8sStepCommand'),
        ),
        migrations.RemoveField(
            model_name='k8sstepcommand',
            name='job_settings',
        ),
    ]
