# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-19 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0089_auto_20190218_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8sstepcommand',
            name='cpu',
            field=models.IntegerField(help_text='Number of cpus to request when running this step command'),
        ),
    ]
