# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-10-21 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0090_workflowversiontooldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDebugURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to where a user can debug a job')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Authorized'), ('S', 'Starting'), ('R', 'Running'), ('F', 'Finished'), ('E', 'Error'), ('c', 'Canceling'), ('C', 'Canceled'), ('r', 'Restarting'), ('D', 'Deleted'), ('e', 'Setting up Debug'), ('d', 'Debug'), ('f', 'Cleaning up Debug')], default='N', help_text='High level state of the project', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Authorized'), ('S', 'Starting'), ('R', 'Running'), ('F', 'Finished'), ('E', 'Error'), ('c', 'Canceling'), ('C', 'Canceled'), ('r', 'Restarting'), ('D', 'Deleted'), ('e', 'Setting up Debug'), ('d', 'Debug'), ('f', 'Cleaning up Debug')], default='N', help_text='High level state of the project', max_length=1),
        ),
        migrations.AddField(
            model_name='jobdebugurl',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debug_url', to='data.Job'),
        ),
    ]
