# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-19 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0090_auto_20190219_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='k8sstepcommand',
            old_name='cpu',
            new_name='cpus',
        ),
    ]
