# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0091_auto_20190219_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8scommandset',
            name='job_settings',
            field=models.OneToOneField(help_text='job settings', on_delete=django.db.models.deletion.CASCADE, related_name='k8s_command_set', to='data.JobSettings'),
        ),
    ]
