# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-19 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0092_auto_20190219_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k8scommandset',
            name='job_settings',
        ),
        migrations.RemoveField(
            model_name='vmcommand',
            name='job_settings',
        ),
    ]
