# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0093_auto_20190219_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsettings',
            name='k8s_command_set',
            field=models.ForeignKey(help_text='K8s command set to use for type k8s', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.K8sCommandSet'),
        ),
        migrations.AddField(
            model_name='jobsettings',
            name='vm_command',
            field=models.ForeignKey(help_text='VM command to use for type vm', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.VMCommand'),
        ),
        migrations.AlterField(
            model_name='jobsettings',
            name='settings_type',
            field=models.CharField(choices=[('vm', 'VM Job Settings'), ('k8s', 'K8s Job Settings')], default='vm', max_length=255),
        ),
    ]
