# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-19 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0094_auto_20190219_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsettings',
            name='settings_type',
        ),
        migrations.AddField(
            model_name='landoconnection',
            name='cluster_type',
            field=models.CharField(choices=[('vm', 'VM Cluster Type'), ('k8s', 'K8s Cluster Type')], default='vm', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsettings',
            name='k8s_command_set',
            field=models.ForeignKey(blank=True, help_text='K8s command set to use for type k8s', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.K8sCommandSet'),
        ),
        migrations.AlterField(
            model_name='jobsettings',
            name='lando_connection',
            field=models.ForeignKey(help_text='Lando connection to use for this job settings', on_delete=django.db.models.deletion.CASCADE, to='data.LandoConnection'),
        ),
        migrations.AlterField(
            model_name='jobsettings',
            name='vm_command',
            field=models.ForeignKey(blank=True, help_text='VM command to use for type vm', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.VMCommand'),
        ),
    ]
